b = int(input('base do retângulo:  '))
a = int(input('altura do retângulo:  '))
area = str(a*b)
perimetro = str((2*a) + (2*b))
print('')
print('Área = '+area)
print('Perímetro = '+perimetro)
input()