brancos = int(input('Qual a quantidade de votos brancos?  '))
nulos = int(input('nulos?  '))
validos = int(input('válidos?  '))
total = brancos + nulos + validos
b = brancos/(total/100)
n = nulos/(total/100)
v = validos/(total/100)
print('============================================')
print('Total de porcentagens')
print('')
print('Total de votos em branco:  ' +str(b)+ '%')
print('Total de votos nulos:  ' +str(n)+ '%')
print('Total de votos válidos:  ' +str(v)+ '%')
input()
